// 12 types of preparedness (Platonov) — full version with group/icon/color/description/source
export const PREPAREDNESS_TYPES = [
  // 5 основних
  {
    key: "physical",
    label: "Фізична",
    group: "Основні",
    icon: "💪",
    color: "hsl(84,81%,44%)",
    description:
      "Рівень розвитку фізичних якостей (сила, витривалість, швидкість, гнучкість, координація)",
    source: "Тести ДЮСШ",
  },
  {
    key: "technical",
    label: "Технічна",
    group: "Основні",
    icon: "🎯",
    color: "hsl(45,90%,55%)",
    description:
      "Рівень технічної майстерності, точність виконання ігрових дій",
    source: "Оцінка тренера",
  },
  {
    key: "tactical",
    label: "Тактична",
    group: "Основні",
    icon: "♟️",
    color: "hsl(200,70%,50%)",
    description: "Здатність вирішувати ігрові ситуації, читати гру",
    source: "Оцінка тренера",
  },
  {
    key: "psychological",
    label: "Психологічна",
    group: "Основні",
    icon: "🧠",
    color: "hsl(340,75%,55%)",
    description: "Вольові якості, стресостійкість, мотивація, концентрація",
    source: "Оцінка тренера",
  },
  {
    key: "theoretical",
    label: "Теоретична",
    group: "Основні",
    icon: "📚",
    color: "hsl(270,65%,60%)",
    description: "Знання правил, тактичних схем, теорії тренування",
    source: "Теоретичний тест",
  },
  // 5 розширених
  {
    key: "functional",
    label: "Функціональна",
    group: "Розширені",
    icon: "❤️",
    color: "hsl(0,75%,55%)",
    description: "Стан серцево-судинної, дихальної систем; ЧСС, МСК",
    source: "Функц. тести",
  },
  {
    key: "psychophysio",
    label: "Психофізіологічна",
    group: "Розширені",
    icon: "⚡",
    color: "hsl(30,80%,55%)",
    description: "Швидкість реакції, увага, сенсомоторна координація",
    source: "Оцінка тренера",
  },
  {
    key: "cognitive",
    label: "Когнітивна",
    group: "Розширені",
    icon: "🔬",
    color: "hsl(160,60%,45%)",
    description: "Оперативне мислення, пам'ять, прийняття рішень під тиском",
    source: "Оцінка тренера",
  },
  {
    key: "morphofunc",
    label: "Морфофункціональна",
    group: "Розширені",
    icon: "📏",
    color: "hsl(190,65%,45%)",
    description: "Антропометрія: зріст, вага, розмах рук, склад тіла",
    source: "Антропометрія",
  },
  {
    key: "recovery",
    label: "Відновлювальна",
    group: "Розширені",
    icon: "🔄",
    color: "hsl(120,55%,45%)",
    description:
      "Здатність до відновлення після навантажень, адаптаційний резерв",
    source: "Оцінка тренера",
  },
  // 2 додаткових
  {
    key: "coordination",
    label: "Координаційна",
    group: "Додаткові",
    icon: "🤸",
    color: "hsl(60,85%,50%)",
    description: "Спеціальна координація рухів: рівновага, ритм, диференціація",
    source: "Тести ДЮСШ",
  },
  {
    key: "integral",
    label: "Інтегральна",
    group: "Додаткові",
    icon: "🏆",
    color: "hsl(84,81%,44%)",
    description:
      "Узагальнений результат взаємодії всіх компонентів. ІГС = 0.4·Ф + 0.25·Т + 0.2·Такт + 0.15·Пс",
    source: "Авто: ІГС",
  },
] as const;
